<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actuationConflictManagement" nsURI="http://i3s.unice.fr/sparks/ACM"
    nsPrefix="actuationConflictManagement">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareComponent" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_parent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalProcess" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ACMComponent" eSuperTypes="#//SoftwareComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acmtype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionComponent" eSuperTypes="#//SoftwareComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalprocess" upperBound="-1"
        eType="#//PhysicalProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor" eSuperTypes="#//ACMComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentLink" eSuperTypes="#//Link">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="monitorToAction"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="monitorToAction" value="self.from.oclIsKindOf(Monitor) implies self.to.oclIsKindOf(ActionComponent)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//SoftwareComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//SoftwareComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemIoT">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSoftwareComponents"
        upperBound="-1" eType="#//SoftwareComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLinks" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalProcesses"
        upperBound="-1" eType="#//PhysicalProcess" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
